---
title: "R Notebook"
output: html_notebook
---
```{r}
library (data.table)
library (ComplexHeatmap)
library (circlize)
library (ggplot2)
library (magrittr)


today <- function(){
  format(Sys.time(), "%Y_%m_%d")
}
DateFileName <- function(x){
  name <-   paste0(today(), "_", x)
  print (name)
  return (name)
}
```





# Load some flu data from the database

```{R}

library(RMariaDB)
library(DBI)

#load data from database

#clean up any connections, print but otherwise ignore any errors
#helpful during development to not keep opening connections while debugging
#tryCatch(dbDisconnect(con), error = function(e) message(e))

con <- dbConnect (RMariaDB::MariaDB(), host="localhost", dbname="fluomics")
foldChanges <- as.data.table(dbGetQuery (con, "select * from fold_change where cell in ('mouse');"))
dbDisconnect(con)


foldChanges <- foldChanges[omics_type %in% c("RNAseq","AB","UB-site","PH-site"),]

removeInfinitesWithLowReplicates <- function(foldChanges, numBioRep = 2, infiniteValue = 1e5){
  nonInfinites <- foldChanges[log2FC > -infiniteValue & log2FC < infiniteValue]
  negInfinites <- foldChanges[log2FC <= -infiniteValue & negative_bio_replicates >= numBioRep,]
  posInfinites <- foldChanges[log2FC >= infiniteValue & positive_bio_replicates >= numBioRep,]
  return (rbind(nonInfinites,negInfinites,posInfinites))
}

str(foldChanges)

foldChanges <- removeInfinitesWithLowReplicates(foldChanges, numBioRep=2)

foldChanges[,experiment_id := paste(omics_type, cell, virus, hours, sep="_")]

foldChanges[,.N, by = experiment_id]

foldChanges[abs(log2FC  > 0) & adj_pvalue < 0.05,.N, by = experiment_id]

# protein identifiers are stored in different places in the databse.  I want to get everyhing in gene

foldChanges[is.na(gene), .N, by = .(omics_type, virus)]
```




```{r}
source ("../../bp_utils/UniprotIDMapping.R")# we want everything in uniprot
foldChanges[is.na(uniprot) & !is.na(protein), uniprot := protein]
#foldChanges[is.na(uniprot) & !is.na(gene), uniprot := translateGeneName2Uniprot(gene, species = "MOUSE")]

foldChanges[!is.na(uniprot),length(unique(uniprot)), by = .(omics_type, virus, hours)]

```

# collapse time points
```{r}
startHeats <- foldChanges[abs(log2FC) < 1e3 & !is.na(uniprot) & !is.na(pvalue) & pvalue > 0, .(maxNegLogP = max(-log10(pvalue), na.rm=TRUE)), by = .(omics_type, virus, uniprot)]

startHeats[,gene := translateUniprot2String(uniprot)]
startHeats[,group := paste(omics_type, virus, sep = "_")]
setnames(startHeats, old = "maxNegLogP", "heat")
unique(startHeats$group)
```

# all network propagation

```{R}
source ("../../bp_utils/NetworkPropagation.R")

```


## network prop
```{r}
library (RcppCNPy)
S_matrix <- RcppCNPy::npyLoad("../network_propagation/S_matrix.mouse.string.gt600.pr0.20.npy")
nodeNames <- fread ("../network_propagation/S_matrix.mouse.string.gt600.pr0.20.nodeNames.csv")[,gene_name]

```