

#  Some documentation auto-generated by chatgpt



# Building up json job files for AF server ----
  #
  # These functions convert sets of protein sequences into the JSON format
  # expected by the AlphaFold Server. Each top-level element represents one job,
  # and each job contains one or more protein chains.
  # =============================================================================

#' Create a protein chain specification
#'
#' Builds the JSON object describing a single protein chain for an
#' AlphaFold Server job.
#'
#' @param seq Character string containing the amino acid sequence.
#' @param N Integer giving the number of copies of this chain in the complex.
#'   Defaults to 1.
#'
#' @return A list formatted as an AlphaFold Server protein chain entry.
singleSeqJsonList <- function (seq, N = 1){
  list(proteinChain = list(sequence = seq, count = N) )
}

#' Build a single AlphaFold Server job
#'
#' Converts one set of protein sequences into a single AlphaFold Server
#' job specification.
#'
#' @param namedSeqs A character vector of protein sequences. Names are ignored
#'   because AlphaFold Server identifies chains by their order rather than
#'   by name.
#' @param jobName Character string giving the job name.
#'
#' @return A list representing one AlphaFold Server job.
buildOneJobJsonList <- function(namedSeqs, jobName){
  seqList <- lapply (setNames(namedSeqs, NULL), singleSeqJsonList)
  
  list( 
    name = jobName,
    modelSeeds = list(), #empty list if unseeded, unsure of what it is when seeded
    sequences = seqList,
    dialect = "alphafoldserver",
    version = 1
  ) 
}


#' Build multiple AlphaFold Server jobs
#'
#' Converts multiple sequence sets into a list of AlphaFold Server jobs.
#'
#' @param seqSetList A list where each element is a character vector of
#'   protein sequences for one prediction job.
#' @param seqSetNames Character vector giving the job name for each sequence
#'   set.
#'
#' @return A list of AlphaFold Server job specifications.
buildMultiJobJsonList <- function(seqSetList, seqSetNames){
  jobList <- purrr::map2(seqSetList, seqSetNames, buildOneJobJsonList)
  names(jobList) <- NULL
  return (jobList)
  
}

#' Write AlphaFold Server job JSON
#'
#' Creates a JSON file containing one or more AlphaFold Server prediction jobs.
#'
#' @param seqSets Named list of sequence sets. Each element should be a
#'   character vector of protein sequences. List names become job names.
#' @param path Output path for the JSON file.
#'
#' @return Invisibly writes a JSON file to disk.
writeAF3JsonForSequenceSets <- function(seqSets, path){
  json <- buildMultiJobJsonList(seqSets, names(seqSets))
  jsonlite::write_json(json, path, auto_unbox = TRUE, pretty = TRUE)
}



# Reading AF3 output ----
#' Read confidence scores from an AlphaFold Server summary JSON
#'
#' Reads a single `summary_confidences_*.json` file produced by the
#' AlphaFold Server and extracts overall model scores together with
#' pairwise interface pTM (ipTM) scores for every unique pair of chains.
#'
#' The returned table contains one row per chain pair within the model.
#' Job names and model numbers are inferred from the filename.
#'
#' If the job name consists of underscore-separated protein names (for
#' example `"ProteinA_ProteinB_ProteinC"`), those names are added to the
#' output as `prot1` and `prot2`.
#'
#' @param file Path to a `summary_confidences_*.json` file generated by the
#'   AlphaFold Server.
#'
#'  @param chainNamesInFileName "check" (default), TRUE, FALSE. Should names
#'      of prot1 and prot2 be pulled from the file name, expecting "_" separator
#'      other values same as FALSE
#'
#' @return A `data.table` containing one row for each unique protein pair with
#'' the following columns:
#' \describe{
#'   \item{job}{Job name extracted from the filename.}
#'   \item{modelnum}{Model number extracted from the filename.}
#'   \item{iptm}{Overall interface pTM score for the model.}
#'   \item{ptm}{Overall pTM score for the model.}
#'   \item{rankingScore}{AlphaFold ranking score.}
#'   \item{protIdx1, protIdx2}{Indices of the interacting protein chains.}
#'   \item{pairIptm}{Pairwise interface pTM score for the chain pair.}
#'   \item{prot1, prot2}{Protein names, when recoverable from the job name.}
#' }
readScoresFromAFSummaryFile <- function(file, chainNamesInFileName = "check"){
  jobname <- stringr::str_extract(file, "(?<=fold_)[^/]*(?=_summary)")
  modelnum <- stringr::str_extract(file, "\\d+(?=\\.json$)") |> as.integer()
  json <- jsonlite::read_json(file)
  
  
  
  
  iptms <- json[["chain_pair_iptm"]]
  nchains <- length(iptms)
  fulliptms <- lapply(1:(nchains-1), function(protein_index_1){
    lapply((protein_index_1+1):nchains, function(protein_index_2){ 
      return(data.table(job = jobname, modelnum= modelnum,
                        iptm = json$iptm, ptm = json$ptm, rankingScore = json$ranking_score,
                        protIdx1 = protein_index_1, protIdx2 = protein_index_2,
                        pairIptm = iptms[[protein_index_1]][[protein_index_2]]))}
    )}) |> unlist(recursive = FALSE) |> rbindlist()
  
  # protein names where the job seems to carry them:
  jobParts <- unlist(strsplit(jobname, "_"))
  if (chainNamesInFileName  == "check" & length(jobParts) == nchains{
     message ("Using file name parts as chain names, set chainNamesInFileName = FALSE to disable")
     chainNamesInFileName <- TRUE
  }
  
  if (chainNamesInFileName == TRUE){
    fulliptms[, prot1 := jobParts[protIdx1]]
    fulliptms[, prot2 := jobParts[protIdx2]]
  }
  
  fulliptms[]
}


#' Read AlphaFold Server confidence scores from a ZIP archive
#'
#' Extracts all `summary_confidences_*.json` files from an AlphaFold Server
#' results archive, reads each summary using
#' `readScoresFromAFSummaryFile()`, and combines the results into a single
#' `data.table`.
#'
#' Summary files are temporarily extracted to a temporary directory, which is
#' cleaned up after processing.
#'
#' @param zipFile Path to an AlphaFold Server results ZIP archive.
#'
#' @return A `data.table` containing confidence metrics for every model and
#'   every protein pair found in the archive.
#'   
readScoresFromZipFile <- function(zipFile){
  unpackPath <- tempfile()
  dir.create(unpackPath)
  
  
  filesTable <- unzip(zipFile, exdir = unpackPath, list = TRUE)
  confFiles <-  grep("summary_confidences", filesTable$Name, value = TRUE)
  
  message ("Unzipping to temp directory at ", unpackPath)
  unzip(zipFile, exdir = unpackPath, files =confFiles)
  confPaths <- file.path(unpackPath, confFiles) 
  allScores <- rbindlist ( lapply (confPaths, readScoresFromAFSummaryFile))
  
  message ("Removing unzipped files at ", unpackPath)
  file.remove (confPaths)
 
  return (allScores[])
}